### Create a 1D NumPy array containing the integers from 0 to 9.

In [5]:
import numpy as np

array_1d = np.arange(10)
print("1D array:", array_1d)


1D array: [0 1 2 3 4 5 6 7 8 9]


### Create a 2D NumPy array (3x3) containing random integers between 1 and 20.

In [2]:
array_2d = np.random.randint(1, 21, size=(3, 3))
print("2D array:\n", array_2d)


2D array:
 [[18  1 13]
 [ 5  4  1]
 [ 7  9  5]]


### Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.

In [3]:
array_3d = np.ones((2, 3, 4))
print("3D array:\n", array_3d)


3D array:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Add two 1D arrays element-wise.

In [4]:
array1 = np.array([7, 2, 34, 4])
array2 = np.array([51, 16, 79, 8])
sum_array = np.add(array1, array2)
print("sum:", sum_array)


sum: [ 58  18 113  12]


### Multiply two 2D arrays element-wisey)


In [7]:
array3 = np.array([[1, 2], [3, 4]])
array4 = np.array([[5, 6], [7, 8]])
product_array = np.multiply(array3, array4)
print("product:\n", product_array)


product:
 [[ 5 12]
 [21 32]]


### Calculate the dot product of two matrices.

In [8]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix1, matrix2)
print("Dot product:\n", dot_product)


Dot product:
 [[19 22]
 [43 50]]


### Calculate the mean, median, and standard deviation of a 1D array.

In [9]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


### Find the maximum and minimum values in a 2D array.

In [10]:
array_2d_2 = np.random.randint(1, 101, size=(3, 3))
max_value = np.max(array_2d_2)
min_value = np.min(array_2d_2)
print("2D array:\n", array_2d_2)
print("Maximum value:", max_value)
print("Minimum value:", min_value)


2D array:
 [[95 46 29]
 [28 93 74]
 [66 44 40]]
Maximum value: 95
Minimum value: 28


### Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1

In [11]:
normal_dist = np.random.normal(0, 1, 1000)
print("Array of 1000 random numbers from normal distribution:", normal_dist)


Array of 1000 random numbers from normal distribution: [ 1.80070009e-01 -4.26354825e-01 -9.57541469e-01  6.61680663e-03
  2.37093209e-01  1.98698264e+00  6.70320687e-01  1.10826577e+00
 -1.81062621e+00  2.97317416e-01  1.52628108e-01  1.44577688e+00
  8.15053285e-01 -3.00024956e-01 -7.51150591e-02  6.62593280e-01
 -8.41428391e-01  9.31221542e-01  1.33082433e+00 -7.85436899e-01
 -2.16412202e+00 -1.41740045e-01 -4.48439252e-01 -1.91003441e-01
  3.92305732e-01 -1.19761272e-01 -3.06258485e-01 -5.63879161e-01
 -2.16290211e-01  5.46297428e-02  4.61018134e-01 -1.01044303e-01
 -1.07966919e+00  9.73136486e-02 -2.76494804e-01  1.86462990e+00
 -1.53316394e+00  1.92452475e+00  7.68810107e-01 -1.96574481e-01
 -6.86471965e-01  1.63066179e+00  2.20865719e-01 -1.71109363e+00
 -8.65150503e-01  5.12647817e-01  9.48964700e-01 -3.56327601e-01
 -4.33692849e-02  6.15026978e-01  7.89042022e-02  4.34817033e-01
  2.34252728e-01  2.76262966e-01 -5.47666473e-01 -1.46592021e+00
  9.67459173e-01  1.58226603e+00 -3

### Create a 2D array of shape (5, 5) with random integers from a uniform distribution between 10 and 50.

In [12]:
 array_2d_uniform = np.random.randint(10, 51, size=(5, 5))
print("2D array of shape (5, 5):\n", array_2d_uniform)


2D array of shape (5, 5):
 [[30 43 21 46 48]
 [30 17 39 16 37]
 [37 24 39 12 47]
 [46 36 45 15 25]
 [26 32 43 35 20]]
