#### Task 1: Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1)
 

In [10]:
import numpy as np

array_2d_example = np.random.randint(1, 21, size=(6, 6))
sub_array = array_2d_example[1:3, 1:3]
print("2D array:\n", array_2d_example)
print("Extracted 2x2 sub-array:\n", sub_array)

2D array:
 [[ 3 18  3  3 11 17]
 [12 20 19 16 10  3]
 [ 9 20 10  4  9 13]
 [17  8 13 16  8 19]
 [19  6  5 12 17 12]
 [ 1  4 17 10  4  8]]
Extracted 2x2 sub-array:
 [[20 19]
 [20 10]]


#### Task 2: From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axisnts)


In [12]:
 
array_3d_example = np.random.randint(1, 21, size=(3, 2, 1))
extracted_elements = array_3d_example[:2, :, 0]
print("3D array:\n", array_3d_example)
print("Extracted elements:\n", extracted_elements)


3D array:
 [[[ 1]
  [ 6]]

 [[13]
  [ 9]]

 [[ 1]
  [ 5]]]
Extracted elements:
 [[ 1  6]
 [13  9]]


#### Task 3: Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6]
```pythonnts)


In [13]:
array_ints = np.array([0, 10, 20, 30, 40, 50, 60, 70])
fancy_indexed_elements = array_ints[[1, 3, 4, 6]]
print("Array:", array_ints)
print("Elements at positions [1, 3, 4, 6]:", fancy_indexed_elements)


Array: [ 0 10 20 30 40 50 60 70]
Elements at positions [1, 3, 4, 6]: [10 30 40 60]


#### Task 4: Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3]
```pythonrray)


In [14]:
array_2d_example = np.random.randint(1, 21, size=(4, 5))
fancy_indexed_sub_array = array_2d_example[[0, 2, 2], :][:, [1, 3]]
print("2D array:\n", array_2d_example)
print("Selected rows [0, 2, 2] and columns [1, 3]:\n", fancy_indexed_sub_array)

2D array:
 [[17  6 11 16 11]
 [ 8 19  2 15  8]
 [17 19  5 13 13]
 [ 3 15 19 17  7]]
Selected rows [0, 2, 2] and columns [1, 3]:
 [[ 6 16]
 [19 13]
 [19 13]]


#### Task 5: From a 1D array of random integers, extract all elements that are greater than 8
```pythonan_8)


In [15]:
array_1d_random = np.random.randint(1, 20, size=10)
elements_greater_than_8 = array_1d_random[array_1d_random > 8]
print("1D array:", array_1d_random)
print("Elements greater than 8:", elements_greater_than_8)

1D array: [ 8 14  6 16 15  7 13 18  2 17]
Elements greater than 8: [14 16 15 13 18 17]


#### Task 6: Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0le)


In [17]:

array_2d_example = np.random.randint(1, 21, size=(6, 6))
array_2d_example[array_2d_example > 13] = 0
print("Modified 2D array:\n", array_2d_example)

Modified 2D array:
 [[ 2 10 11  8  0 12]
 [ 9  9 13 13  4  0]
 [13  3  0  0  0  1]
 [ 0  4  8  1  0 10]
 [ 5  0  0  7  6  3]
 [ 4 12 10  3  4 13]]


# BroadCasting

#### Task 1: Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3)
```python



In [18]:
array_1d = np.array([1, 2, 3])
array_2d = np.random.randint(1, 10, size=(4, 3))
result = array_2d + array_1d
print("1D array:", array_1d)
print("2D array:\n", array_2d)
print("Result of broadcasting:\n", result)

1D array: [1 2 3]
2D array:
 [[2 3 6]
 [1 1 2]
 [5 8 7]
 [5 1 4]]
Result of broadcasting:
 [[ 3  5  9]
 [ 2  3  5]
 [ 6 10 10]
 [ 6  3  7]]


#### Task 2: Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,)
```pythonesult)


In [19]:
array_2d = np.random.randint(1, 10, size=(3, 3))
array_1d = np.array([1, 2, 3])
result = array_2d * array_1d
print("2D array:\n", array_2d)
print("1D array:", array_1d)
print("Result of broadcasting:\n", result)


2D array:
 [[8 6 1]
 [6 2 7]
 [8 5 2]]
1D array: [1 2 3]
Result of broadcasting:
 [[ 8 12  3]
 [ 6  4 21]
 [ 8 10  6]]


#### Task 3: Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition
```pythonresult)


In [20]:
array_2d_1 = np.random.randint(1, 10, size=(3, 1))
array_2d_2 = np.random.randint(1, 10, size=(1, 4))
result = array_2d_1 + array_2d_2
print("Array of shape (3, 1):\n", array_2d_1)
print("Array of shape (1, 4):\n", array_2d_2)
print("Result of broadcasting:\n", result)

Array of shape (3, 1):
 [[4]
 [5]
 [7]]
Array of shape (1, 4):
 [[9 5 4 6]]
Result of broadcasting:
 [[13  9  8 10]
 [14 10  9 11]
 [16 12 11 13]]


#### Task 4: Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis
```python



In [22]:
array_3d = np.random.randint(1, 10, size=(2, 3, 4))
array_2d = np.random.randint(1, 10, size=(3, 4))
result = array_3d + array_2d
print("3D array:\n", array_3d)
print("2D array:\n", array_2d)
print("Result of broadcasting:\n", result)

3D array:
 [[[6 5 5 3]
  [5 6 2 2]
  [4 9 2 2]]

 [[2 8 7 6]
  [8 4 5 3]
  [4 1 8 9]]]
2D array:
 [[8 4 4 7]
 [1 3 5 3]
 [2 5 8 7]]
Result of broadcasting:
 [[[14  9  9 10]
  [ 6  9  7  5]
  [ 6 14 10  9]]

 [[10 12 11 13]
  [ 9  7 10  6]
  [ 6  6 16 16]]]


#### Task 5: Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array
```python



In [23]:
array_2d = np.random.randint(1, 20, size=(6, 6))
sliced_array = array_2d[::2, ::2]
array_1d = np.random.randint(1, 10, size=(sliced_array.shape[1]))
result = sliced_array + array_1d
print("Original 2D array:\n", array_2d)
print("Sliced array (every second row and column):\n", sliced_array)
print("1D array:", array_1d)
print("Result after adding 1D array to each row:\n", result)

Original 2D array:
 [[ 5 18 10 19 18 17]
 [ 3  4 11  6 13 17]
 [13 16 10  8 14  2]
 [16  8 18 16 13 13]
 [13  6 11  4  8  9]
 [ 3 19 16 16 17 18]]
Sliced array (every second row and column):
 [[ 5 10 18]
 [13 10 14]
 [13 11  8]]
1D array: [5 4 3]
Result after adding 1D array to each row:
 [[10 14 21]
 [18 14 17]
 [18 15 11]]
